### ISSUE TITLE
.Rmd to pull responses from google sheets

### ISSUE THREAD

**Issue by ccmothes** [rossyndicate/sow_shiny#1]
Take notes on which questions in the google form could be modified to make this easier

**Comment by juandlt-csu** [comment]
I think these would be the easiest things to change to make the form responses more usable on our end:

- Split timeframe question into beginning and end dates for the project.
- Specify that users should input tasks and deliverables as bullet points.
- Formal contract question should have yes/no/I don’t know

@ccmothes
